apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-cf-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
        - name: app-test-1
          image: nginx
          ports:
            - name: web
              containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-cf-dev
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
