apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-test-1-deploy
  namespace: app-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-test-1
  template:
    metadata:
      labels:
        app: app-test-1
    spec:
      containers:
        - name: app-test-1
          image: nginx
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - name: web
              containerPort: 80
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  name: app-test-1-svc
  namespace: app-dev
  labels:
    app: app-test-1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: app-test-1
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-test-1-ingress
  namespace: app-dev
# annotations:
#   traefik.ingress.kubernetes.io/router.tls: "true"
#   cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
    - host: "ad.test-002.xcv.my.id"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: app-test-1-svc
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - ad.test-002.xcv.my.id
  #     secretName: app-test-1-tls-secret1
